# Site settings
title: codEnergy website
description: > 
  This website regroups all charts created in order to study the energy distribution of software through methods.
baseurl: "/codEnergy"

# Build settings
markdown: kramdown

highlighter: pygments

charts_dir: charts

exclude: ['README.md', "LICENSE", ".DS_Store"]