# Basic site settings
title: codEnergy website
author: Maxime Colmant
description: >
  Studying the software energy distribution over methods
baseurl: "/codEnergy"

# InfluxDB settings
influxHost: "spirals-codenergy.lille.inria.fr"
influxPort: "8086"
influxDB: "codenergy"
influxUser: "web"
influxPwd: "web"

# TypeScript settings
js_dest: js

# Build settings
markdown: kramdown
highlighter: pygments
exclude: ['README.md', "LICENSE", ".DS_Store"]
